import type { Metadata } from "next";
// import { Open_Sans, Cairo } from "next/font/google";
import "../../styles/globals.css";
import Providers from "../ServerProviders";
import { routing } from "@/i18n/routing";
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";


// const plexMomo = Cairo({
//   variable: "--font-app",
//   display: "swap",
//   subsets: ["latin"],
//   weight: ["200", "300", "400", "500", "600", "700"],
// });

// const openSans = Open_Sans({
//   subsets: ['latin'],
//   variable: '--font-open-sans',
//   weight: ['400', '600', '700'], // adjust as needed
//   display: 'swap',
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  //className={`${plexMomo.variable} ${openSans.variable}`} 

  return (
    <html lang={locale} dir={locale == 'en' ? 'ltr' : 'rtl'}>
      <body
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
